language: python
python:
  - "3.10"

install:
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-mock coverage requests-mock"
script:
  - coverage run -m pytest
after_success:
  - coveralls
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
