language: python
python:
  - "3.9"

install:
  - "pip install ."
  - "pip install pytest pytest-mock coverage requests-mock"
script:
  - coverage run -m pytest
after_success:
  - coveralls
  - coverage xml
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml; fi
